name: Create Ubuntu and Window Releases

on: 
  push:
    tags:
    - '*'
    
  workflow_dispatch:
jobs:
  build-linux:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: docker pull debenham/xlights
      - run: docker run --name buildvm debenham/xlights /bin/bash Recipe.appimage
      - run: 'docker cp buildvm:/xLights/xLights/AppImage/ /tmp/'
      - run: ls -lh /tmp/AppImage

      - uses: ncipollo/release-action@v1
        with:
           allowUpdates: true
           artifacts: "/tmp/AppImage/*.AppImage"
           token: ${{ secrets.GITHUB_TOKEN }}
           
  build-windows:
   runs-on: windows-2022

   steps:
    - name: Checkout xLights
      run: git clone https://github.com/smeighan/xLights.git C:/xLights/ --depth 1  --depth=1 --shallow-submodules --recurse-submodules

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Download wxWidgets
      run: 
        git clone --depth=1 --shallow-submodules  --recurse-submodules -b xlights_2023.11 https://github.com/xLightsSequencer/wxWidgets C:/wxWidgets/

    - name: Build wxWidgets
      working-directory: C:/wxWidgets/
      run: msbuild /m .\build\msw\wx_vc16.sln /p:Configuration="Release" /p:Platform="x64"

    - name: Build All
      shell: cmd
      working-directory: C:/xLights/build_scripts/msw
      run: call build_VS_x64_skip_libltc.cmd

    - name: Build Installer
      working-directory: C:/xLights/build_scripts/msw
      run: ISCC.exe xLights_4_64bit_VS.iss
      
    - uses: ncipollo/release-action@v1
      with:
           allowUpdates: true
           artifacts: 'C:\xLights\build_scripts\msw\output\*'
           token: ${{ secrets.GITHUB_TOKEN }}
