name: Windows Nightly

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: 'true'

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1     
            
    - name: install Inno
      run: choco install innosetup   
      
    - name: install python dependency
      run: pip install in_place  
      
    - name: generate nightly version number
      working-directory: build_scripts\msw
      run: python WriteNightlyVersionFiles.py  
     
    - name: Download wxWidgets
      run: 
        git clone --depth=1 --shallow-submodules  --recurse-submodules -b xlights_2022.09 https://github.com/xLightsSequencer/wxWidgets ..\wxWidgets\

    - name: Build wxWidgets
      working-directory: ..\wxWidgets\
      run: msbuild /m .\build\msw\wx_vc16.sln /p:Configuration="Release" /p:Platform="x64"
      
    - name: Build xlDo
      working-directory: xlDo
      run: msbuild xlDo.sln /m /p:Configuration="Release" /p:Platform="x64"
    - name: Build xFade
      working-directory: xFade
      run: msbuild xFade.sln /m /p:Configuration="Release" /p:Platform="x64"
     
    - name: Build xCapture
      working-directory: xCapture
      run: msbuild xCapture.sln /m /p:Configuration="Release" /p:Platform="x64"
     
    - name: Build xScanner
      working-directory: xScanner
      run: msbuild xScanner.sln /m /p:Configuration="Release" /p:Platform="x64"
      
    - name: Build xSchedule
      working-directory: xSchedule
      run: msbuild xSchedule.sln -maxcpucount:4 /p:Configuration="Release" /p:Platform="x64"
      
    - name: Build xSMSDaemon
      working-directory: xSchedule\xSMSDaemon
      run: msbuild xSMSDaemon.sln /m /p:Configuration="Release" /p:Platform="x64"
     
    - name: Build RemoteFalcon
      working-directory: xSchedule\RemoteFalcon
      run: msbuild RemoteFalcon.sln /m /p:Configuration="Release" /p:Platform="x64"

    - name: Build xLights
      working-directory: xLights
      run: msbuild xLights.sln -maxcpucount:2 /p:Configuration="Release" /p:Platform="x64"
      
    - name: Build Installer
      working-directory: build_scripts\msw
      run: ISCC.exe xLights_4_64bit_VS.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v2
      with:
        name: xLights_x64_Installer
        path: 'build_scripts\msw\output\**'
