name: Windows Nightly

on:
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC    
  workflow_dispatch:

jobs:
  check_for_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new commits today
        id: check-new-commits
        uses: adriangl/check-new-commits-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          seconds: 86400 # One day in seconds
          branch: 'master' # Or your target branch
      - name: Set output if new commits found
        if: ${{ steps.check-new-commits.outputs.has-new-commits == 'true' }}
        run: echo "::set-output name=should_run::true"
      - name: Set output if no new commits
        if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
        run: echo "::set-output name=should_run::false"
    outputs:
      should_run: ${{ steps.check-new-commits.outputs.has-new-commits }}

  build:
    needs: check_for_commits
    if: ${{ needs.check_for_commits.outputs.should_run == 'true' }}
    runs-on: windows-2022

    steps:
    - name: Checkout xLights
      uses: actions/checkout@master
      with:
          submodules: 'true'
          
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: install ISPC
      uses: ispc/install-ispc-action@main
      with:
        version: 1.29.1
            
#    - name: install Inno
#      run: choco install innosetup   
      
    - name: install python dependency
      run: pip install in_place  
      
    - name: generate nightly version number
      working-directory: build_scripts\msw
      run: python WriteNightlyVersionFiles.py  
     
    - name: Download wxWidgets
      run: 
        git clone --depth=1 --shallow-submodules  --recurse-submodules -b master https://github.com/xLightsSequencer/wxWidgets ..\wxWidgets\

    - name: Build wxWidgets
      working-directory: ..\wxWidgets\
      run: msbuild /m .\build\msw\wx_vc17.sln /p:Configuration="Release" /p:Platform="x64"
      
    - name: Build All
      shell: cmd
      working-directory: build_scripts\msw
      run: call build_VS_x64_skip_libltc.cmd
      
    - name: Build Installer
      working-directory: build_scripts\msw
      run: ISCC.exe xLights_4_64bit_VS.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: xLights_x64_Installer
        path: 'build_scripts\msw\output\**'
        
    - name: Create prerelease
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "nightly"
        title: "${{ steps.version.outputs.version }}"
        files: |        
          ./build_scripts/msw/output/*.exe

