 
name: Windows_Build


on:
  release:
   created:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Download wxWidgets
      run: 
        git clone --depth=1 --shallow-submodules  --recurse-submodules -b xlights_2021.13 https://github.com/xLightsSequencer/wxWidgets ..\wxWidgets\

    - name: Build wxWidgets
      working-directory: ..\wxWidgets\
      run: msbuild /m .\build\msw\wx_vc16.sln /p:Configuration="Release" /p:Platform="x64"

    - name: Build xFade
      working-directory: xFade
      run: msbuild xFade.sln /m /p:Configuration="Release" /p:Platform="x64"
     
    - name: Build xCapture
      working-directory: xCapture
      run: msbuild xCapture.sln /m /p:Configuration="Release" /p:Platform="x64"
     
    - name: Build xScanner
      working-directory: xScanner
      run: msbuild xScanner.sln /m /p:Configuration="Release" /p:Platform="x64"
      
    - name: Build xSchedule
      working-directory: xSchedule
      run: msbuild xSchedule.sln -maxcpucount:4 /p:Configuration="Release" /p:Platform="x64"
      
    - name: Build xSMSDaemon
      working-directory: xSchedule\xSMSDaemon
      run: msbuild xSMSDaemon.sln /m /p:Configuration="Release" /p:Platform="x64"
     
    - name: Build RemoteFalcon
      working-directory: xSchedule\RemoteFalcon
      run: msbuild RemoteFalcon.sln /m /p:Configuration="Release" /p:Platform="x64"

    - name: Build xLights
      working-directory: xLights
      run: msbuild xLights.sln /p:Configuration="Release" /p:Platform="x64"
      
    - name: Build Installer
      working-directory: build_scripts\msw
      run: ISCC.exe xLights_4_64bit_VS.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v2
      with:
        name: xLights_x64_Installer
        path: 'build_scripts\msw\output\**'

#    - name: Upload xFade.exe
#      uses: actions/upload-artifact@v2
#      with:
#        name: xFade.exe
#        path: xFade\x64\Release\xFade.exe
#
#    - name: Upload xCapture.exe
#      uses: actions/upload-artifact@v2
#      with:
#        name: xCapture.exe
#        path: xCapture\x64\Release\xCapture.exe
#
#    - name: Upload xScanner.exe
#      uses: actions/upload-artifact@v2
#      with:
#        name: xScanner.exe
#        path: xScanner\x64\Release\xScanner.exe
#
#    - name: Upload xSchedule.exe
#      uses: actions/upload-artifact@v2
#      with:
#        name: xSchedule.exe
#        path: xSchedule\x64\Release\xSchedule.exe
#
#    - name: Upload xSMSDaemon.dll
#      uses: actions/upload-artifact@v2
#      with:
#        name: Xsmsdaemon.dll
#        path: xSchedule\xSMSDaemon\x64\Release\Xsmsdaemon.dll
#
#    - name: Upload RemoteFalcon.dll
#      uses: actions/upload-artifact@v2
#      with:
#        name: RemoteFalcon.dll
#        path: xSchedule\RemoteFalcon\x64\Release\RemoteFalcon.dll
#
#    - name: Upload Xlights.exe
#      uses: actions/upload-artifact@v2
#      with:
#        name: Xlights.exe
#        path: xLights\x64\Release\Xlights.exe
